apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notes-app.fullname" . }}-config
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
data:
  MONGO_HOST: "{{ default (printf "%s-mongo-service" .Release.Name) .Values.config.mongoHost }}"
  MONGO_PORT: "{{ .Values.config.mongoPort }}"
  MONGO_DB: "{{ .Values.config.mongoDB }}"
  NODE_ENV: "{{ .Values.config.nodeEnv }}"
