{{- if .Values.mongodb.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "notes-app.fullname" . }}-mongo-pvc
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.pvc.storage }}
{{- end }}
