apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-app.fullname" . }}-mongo-deploy
  labels:
    app: mongo
    {{- include "notes-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.image.mongo.repository }}:{{ .Values.image.mongo.tag }}"
        imagePullPolicy: {{ .Values.image.mongo.pullPolicy }}
        args: ["--auth", "--bind_ip_all"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "notes-app.fullname" . }}-secret
              key: MONGO_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "notes-app.fullname" . }}-secret
              key: MONGO_PASSWORD
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: {{ include "notes-app.fullname" . }}-mongo-pvc
