apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notes-app.fullname" . }}-secret
  labels:
    {{- include "notes-app.labels" . | nindent 4 }}
stringData:
  MONGO_USERNAME: "{{ .Values.secret.mongoUsername }}"
  MONGO_PASSWORD: "{{ .Values.secret.mongoPassword }}"



  
